package pc2.lab.aula09.model.enums;

public enum OpcoesMenuEnum {
    TEXTO, RETA, QUADRADO, RETANGULO, CIRCULO, LOSANGO, TRIANGULO, DESENHAR, LISTAR, APAGAR, SALVAR, RECARREGAR, SAIR,
    NOVO, EDITAR, MOSTRAR, EXCLUIR, VOLTAR

}